INSERT INTO Faculties (FacultyName, FacultyCode) VALUES
('Faculty of Biology', 'FB'),
('Faculty of Geography', 'FG'),
('Faculty of Geology', 'FGL'),
('Faculty of Economics', 'FE'),
('Faculty of Electronics and Computer Technology', 'FECT'),
('Faculty of Journalism', 'FJ'),
('Faculty of Foreign Languages', 'FFL'),
('Faculty of History', 'FH'),
('Faculty of Culture and Arts', 'FCA'),
('Faculty of Mechanics and Mathematics', 'FMM'),
('Faculty of International Relations', 'FIR'),
('Faculty of Pedagogical Education', 'FPE'),
('Faculty of Applied Mathematics and Informatics', 'FAMI'),
('Faculty of Finance and Business Management', 'FFBM'),
('Faculty of Physics', 'FP'),
('Faculty of Philology', 'FPH'),
('Faculty of Philosophy', 'FPY'),
('Faculty of Chemistry', 'FCH'),
('Faculty of Law', 'FL');
